### ISSUE TITLE
Additional units count

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#10]
Should we maybe decrease the units count per spawn to one ?

They would be easier to control (move one tank here, one tank there).

Also, it seems that only the first unit of the group is directly controllable by CA.

As it could become cumbersome to have to do the F10 dance for every unit, I could build a system where the player will select the number of units to spawn.
For example:

```
F10 -> Range options -> Tetra -> Spawn -> MBT -> 5
```
, where "5" would be the count of **individual units** to spawn.

**Comment by 132nd-Entropy** [comment]
the auto-respawn targets will spawn as singles, but sometimes, its easier to move them as a group also, so I dont mind either way. Right now, we have the singletons in the range storage and the groups as the OD spawns, correct? (that would work for me, but dont mind either way)

**Comment by theendsofinvention** [comment]
Indeed; maybe we should have an option to be able to spawn them either as a group, or as singletons?

**Comment by 132nd-Entropy** [comment]
I think its fine as it is tbh, we have singletons from the range, and we have the groups from the OD spawning. I think thats plenty and keeps the menu system not too complicated. but Im fine with either way of course :)
