### ISSUE TITLE
SAR - Hostiles not firing

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#11]
Very often, "hostiles" units do not fire at the downed pilot.

This *seems* to be a LOS issue.

Possible fixes include:

* Have the units circle around the downed pilot until they have LOS
* Have them fire above the downed pilots position
* Compute possible destinations based on valid LOS before having the units moving

**Comment by 132nd-Entropy** [comment]
easiest solution is to find a good spot where there is not too much terrain masking and simply move the potential zones where the crashsite can occur there. But thats quite some work and up to this point Im not even sure people use the CSAR part of the script (with the 'hostiles')

**Comment by theendsofinvention** [comment]
I feel the same. I suggest we leave this open until one of us comes up with
a better implementation.

In the meantime, the current system offers more than enough immersion
factor for this not to be a top priority.

**Comment by 132nd-Entropy** [comment]
closing for now
