### ISSUE TITLE
Create new range - OCA Range - Kutaisi

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#18]
Now with the inclusion of the Mirage Squadron, I have recived a request for a range for conducting OCA operations (Offensive Counter Air).

I will create a new range (with complete Range order) over Kutaisi airfield.

As such, I will also move the current tankers to surrounding airfields, to make Kutaisi deactive as a airfield, and to be working as a range

**Comment by 132nd-Entropy** [comment]
rgr. If red defanged red CAP is desired (misile trainer + no guns), Im happy to implement it as Ive been working with the CAP script on MOOSE before. It needs some more tweaking but I put it completely on hold until I hear if you want it or not, so let me know and I get it done

**Comment by 132ndNeck** [comment]
Thanks, No, I don't think I want to implement RED CAP here. However, on the Standard Combat mission, then there is need for several RED CAP zones. Once I get the a flow from Etcher, I will post the standard combat mission on github.

**Comment by theendsofinvention** [comment]
:+1:

**Comment by 132ndNeck** [comment]
I will start working on the training mission tomorrow, and I will create a OCA range at Kutaisi, I will also add a couple more ranges in the general Kutaisi area (NORTHEAST of Kutaisi).

Anyone have any objections? Or inputs on how to do it? if not, I will do as before with a general range airspace, put out some static targets, and some targets at a "storage" that can be moved around to support the training objectives at that certain area.

PLus I will also add in JTAC's as appropriate.

**Comment by 132ndNeck** [comment]
![kutaisi range tgts](https://cloud.githubusercontent.com/assets/26002570/26223686/7591134c-3c1f-11e7-9c19-83d74e3b8796.png)

Here is how the new range at KUTAISI looks like. It is intended for OCA strikes.
Questions, commentsm concerns?

**Comment by 132ndNeck** [comment]
Range is now created in "my" branch, and ready for merge into develop/master
