### ISSUE TITLE
Migrate to 132nd vWing organization

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#19]
The TRMT repository should be migrated altogether to the 132nd vWing organization, in order to make the administration & user/permission management easier in the future.

Also, the organization should be the default owner for any future repository.

Please note that this does not prevent you from owning your own copy of any repository (a "fork"). This is something we did not use yet, but Git & Github offer a lot of functionalities to work with repositories that are "linked" together, mainly via "Pull requests".

**Comment by theendsofinvention** [comment]
My question is: would this be ok with everyone involved?

If it is, I'll discuss the ownership transfer with Entropy.

Be advised that everyone will have to update the address of their "origin" repo in their local repository (using SmartGit for example).

**Comment by 132ndNeck** [comment]
I am happy for such a migration to take place.
@132nd-etcher, if you could include a flow on how to redirect the local repo in smartgit after such a migration, it will be highly appreciated.

**Comment by theendsofinvention** [comment]
Affirm, will do.

I will also start working on a document outlining all the basic steps needed to obtain a working copy of the repositories, along with the steps to contribute changes to them.

**Comment by 132nd-Entropy** [comment]
@132nd-etcher sry for late response work is crazy today. And yes, of course Im happy with the migration

**Comment by theendsofinvention** [comment]
Absolutely no problem, it's amazing as it is that we have such a fast food
if ideas going on!

I'll prepare an outline of what's needed to be done to ensure a smooth
migration.
