### ISSUE TITLE
Add Role 2 hospital facility close to Lochini

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#20]
As seen in the branch (Neck's edit). This hospital is for medevac for the MI-8.

**Comment by theendsofinvention** [comment]
:+1:

**Comment by 132nd-Entropy** [comment]
awesome idea!!

**Comment by 132ndNeck** [comment]
Added, and was working during the training mission yesterday, so I am closing this issue.
