### ISSUE TITLE
MOOSE updating policy

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#24]
The TRMT uses the well known [MOOSE](https://github.com/FlightControl-Master/MOOSE)  framework.

I would like to discuss our policy on updating it.

A) On one hand, we can stick with the "stable" version, and update very seldom.

B) On the other hand, we could update more often to the latest dev version, and enjoy the latest bugfixes and features, while taking the risk of bugs. This approach would also have the indirect added benefit of helping MOOSE's creator in finding & fixing bugs.

When it comes to implementation, there are 5 options that I can think of:

1. update moose.lua manually.
1. have appveyor automatically pull the latest version during the build (that one raises question about propagating the change back to GH)
1. use a Git hook to pull the file before pushing
1. add the MOOSE repository as a submodule
1. add the MOOSE repository as a subtree

Votes are open ! Mine goes for B5.

**Comment by 132nd-Entropy** [comment]
I agree and also vote B5

**Comment by 132ndNeck** [comment]
I do not know enough about this to cast a vote. But from my limited view, a version of option B is likely the best choice.

**Comment by theendsofinvention** [comment]
Understood, the consensus for B is obvious.

@132nd-Entropy would you mind building & pushing the latest MOOSE from time to time for the time being ? I'll assign this to myself and will work on an automated solution.

**Comment by 132nd-Entropy** [comment]
totally dont mind at all

**Comment by 132nd-Entropy** [comment]
I will periodically update moose and closing this issue
