### ISSUE TITLE
MissileScript issues

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#25]
The missile script has been less reliable lately.

Primary causes of concern are:

* Mirage's missiles
* MANPADS

I create this issue mostly as a note to myself to investigate when able.

**Comment by 132nd-Entropy** [comment]
apparently mirage radar missiles worked, but not IR missiles

**Comment by 132nd-Entropy** [comment]
negative, both IR and Radar missiles shot from a Mirage get picked up by the script I tested so it should work?!

**Comment by theendsofinvention** [comment]
Roger, thank you very much for testing !

So it can be either a corner-case runtime bug, due to the script not catching the missile at all, or an actual logic flaw.

I will add a few debug line to keep track of the tracing (trackception ?) and see what happens in the following events.

Referencing #23 .

**Comment by 132nd-Entropy** [comment]
side note, I tested and now also the manpad missiles seem to be fixed. You get a launch warning now in pit (was bugged before, but apparently ED fixed it) and also the script picks them up just fine

**Comment by theendsofinvention** [comment]
Got it ! Thanks again for testing =)

**Comment by 132nd-Entropy** [comment]
I close this for now as I do think there is no issue with the missile trainer script. We can revisit if it happens again.
