### ISSUE TITLE
Add extra AWACS

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#28]
Add an extra AWACS for to support A-A training. AWACS to be stationed closer to the A-A MOA.

**Comment by theendsofinvention** [comment]
:+1:

**Comment by theendsofinvention** [comment]
Would it be ok to make it start on Kutaisi, like Arco, or would you guys rather like the added traffic in TBI TMA?

**Comment by theendsofinvention** [comment]
@Neck is there a general area you'd like the AWACS track in ?

Also, is it ok to make it start from Kutaisi, like Arco ?

**Comment by 132ndNeck** [comment]
No, nothing can start from Kutaisi, as this will now become a range. So tankers at Kutaisi need to move (either to Senaki, Kobuleti or Batumi).

I would prefer to have the tanker track to the SOUTH. But if you are able to put in the tankers and awacs, then I could adjust it, based on the ranges and Kutaisi range+ MOA (A-A) airspace as required?

**Comment by theendsofinvention** [comment]
Should i refer to Looney WIP document about the MOA to situate the different HAV tracks ?

**Comment by theendsofinvention** [comment]
Roger for starting loc.

**Comment by 132ndNeck** [comment]
You can use that as a baseline, and I can just rearrange if required

**Comment by theendsofinvention** [comment]
Will do

**Comment by 132nd-Entropy** [comment]
closing as the second awacs is in
