### ISSUE TITLE
Refactor support aircrafts (tanker & AWACS) activation

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#29]
The current implementation waits for the tanker/AWACS to shut down its engine, after RTB and landing, before spawning a new one, creating a huge gap in availability.

An more convenient solution would be to spawn the new asset when the one orbiting is about to hit bingo.

The implementation would be something along the lines of:

```
1. Spawn tanker, remember the group
2. Start a scheduler to check for fuel every 10 seconds on group
3. If fuel is low, start new tanker, and replace previous group with new one```

**Comment by 132nd-Entropy** [comment]
suggest to add a check in teh scheduler that fires up a new plane not only when the old tanker is bingo, but also when the old tanker is damaged or killed (such as by accidents during refuelling)

**Comment by theendsofinvention** [comment]
@Neck @Entropy latest develop implements a prototype of a new system for managing tankers & AWACS

There is a test MIZ file on AV, build [269](https://ci.appveyor.com/api/buildjobs/adfu2cc651jat0gm/artifacts/TRMT_2.9.0.269.miz), on branch "test-tanker".

This MIZ has been heavily tweaked:

* All modules except the tanker test are de-activated
* Arco has been disabled
* Texaco start with 21% fuel (threshold is at 20%)
* Texaco orbit is near the Bullseye to shorten travel time

To test, run the MIZ. You should see Texaco take off from Vaziani, orbit until it immediately runs out of fuel, another tanker takes off, while the previous one stays on station, waiting. When the new one arrives, the previous ones heads back home.

There is also a DEBUG menu to destroy any tanker at any point, to check the reaction of the system.

This has been implemented using two new concepts:

* Moose's FSM
* Lua "classes"

I tried to comment the code & the debug message as best as I could.

This will **NOT** be pushed on develop until thoroughly tested.

Cheers =)

**Comment by theendsofinvention** [comment]
I suggest you run the test with LogExpert running in the background to have a real-time view of what's happening internally.

**Comment by 132nd-Entropy** [comment]
tested, seems to be working, awesome job!!
