### ISSUE TITLE
Change tanker TEXACO track to N-S

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#30]
In order to minimize the impact on the new airspaces, I suggest to change the tanker TEXACO track from E-W to N-S.

**Comment by 132ndNeck** [comment]
I have done this in "my" current branch with the new ranges.

**Comment by 132nd-Entropy** [comment]
this should then be included in the latest version
