### ISSUE TITLE
Use "Red" units in .miz: A-A training

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#33]
A suggestion came up after the training event yesterday, to have some of the Mirage agressors be RED, as that triggers an IFF function in the Mirage2000C. I was not aware of that functionality, hence until now there have not really been any need for a "red" units in the missionfile.

However, with that functionality, I see the reason and need to put in red aggressors for Mirage/A-A in order to trigger the correct responses.

Also, the skins of the aggressors, should be very distinct, so that one could seperate the aggressors during dogfights.

This from a request by Bulldog (Since I dont fly the Mirage and dont know the systems)

**Comment by 132ndNeck** [comment]
If we create the red units as specified above, we might aswell, add in a RED AWACS, as it will make the chances for increased AWACS training aswell.

AWACS to be placed in a N-S track just off the Coast

**Comment by 132nd-Entropy** [comment]
red agressor awacs added to the support aircarft code, it will start up from Nalchik and fly to teh track specified. Closing this as I assume its finished
