### ISSUE TITLE
Beacons & TACAN

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#36]
Use MOOSE AATACAN instead of relying on the ME for functionality.

Using MOOSE will allow for a far more flexible & extensible implementation of the TACAN for the tankers.

https://github.com/FlightControl-Master/MOOSE/blob/9984055f7d8d2be658540d83d2338227f42e7e61/Moose%20Development/Moose/Core/Radio.lua#L426

**Comment by theendsofinvention** [comment]
@132nd-Entropy do you have any thoughts about this one ?

**Comment by 132nd-Entropy** [comment]
oh, yeah of course! then we can get rid of the damn mod that gets overriden so often! :)

**Comment by theendsofinvention** [comment]
My thoughts exactly =)

**Comment by 132nd-Entropy** [comment]
I think this can be shelved for now, since we 'solved' it by making the unified tacan eplrs mod

**Comment by theendsofinvention** [comment]
The MOOSE TACAN functionnality would fix the TACAN not being set on the tankers that spawn after the first one, re-opening for later fix.

**Comment by theendsofinvention** [comment]
Hopefully fixed in 3.8.0, waiting on feedback

927fecc9e0e6e7af2ae20e408bd95651ca56481e

**Comment by 132nd-Entropy** [comment]
looks to me its working!

**Comment by theendsofinvention** [comment]
I'll leave it open as a reminder to check on pilots in a while, but I think it's okay now.

**Comment by theendsofinvention** [comment]
Implemented
