### ISSUE TITLE
Support assets blocking each other

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#37]
While testing the tanker re factorization, I had multiple instance of the tankers & the AWACS blocking each other on the taxiway, resulting in a total gridlock, preventing any of them getting airborne from Vaziani.

I would like to change their starting condition from taxiway to runway, to avoid this issue in the future.

Would that be ok with the both of you ?

**Comment by theendsofinvention** [comment]
@132ndNeck @132nd-Entropy bumping the issue

**Comment by 132nd-Entropy** [comment]
Im surprised because we have never had this problem before. I think its cool when they start from the taxiway instead but if it causes problems then yeah I guess we need to fix them by starting from the rwy I guess

**Comment by 132nd-Entropy** [comment]
ok Im closing this for now since we've moved all tankers to individual airports and this is hopefully fixed.
