### ISSUE TITLE
Re-implement airbase clean up

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#38]
Following a talk with FlightControl, the clean up mission has been fixed recently and should be able to help us with the tanker/AWACS issues.

Implementation example can be found [here](https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/master/ACL%20-%20Airbase%20Cleaner/ACL-001%20-%20Airbase%20CleanUp).

**Comment by 132nd-Entropy** [comment]
implemented, but not working for us. Plan still valid to schedule a destroy() 30min after the RTB state?

**Comment by 132nd-Entropy** [comment]
from what I see, we dont need the cleanup (and according some post from Sven, it will use lots of resources). 

my sugggestion: remove the cleanup lines in the TRMT script and add the destroy 30 min after RTB?

**Comment by theendsofinvention** [comment]
This can be done.

I'll take care of it first occasion !

**Comment by 132nd-Entropy** [comment]
I think this is completed, clsing it
