### ISSUE TITLE
Downed pilot to infantry & helicopter

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#4]
During CSAR, a menu should be available to make the downed pilot move towards either:

* the infantry dropped by a Mi8
* the Mi8 itself, provided it's landed in a reasonable radius

**Comment by 132nd-Entropy** [comment]
I think this can be closed since we bypassed the need for that by moving the crash sites to accessible areas only
