### ISSUE TITLE
REDFOR F5s at Lochini unable to start up

### ISSUE THREAD

**Issue by jkhoel** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#49]
Since they are red units at a blue base, you cant interact with the ground crew. Unable to start up w/o air comp.

Suggest either making one of the close-by airports red and move all red units there, or just remove the F5s from Lochini.

**Comment by 132nd-Entropy** [comment]
I did not think of that. well easiest would then be to have them there with engines running imo

**Comment by jkhoel** [comment]
Yea that would work too! And a center tank

**Comment by 132nd-Entropy** [comment]
solved
