### ISSUE TITLE
CSAR spawn points in pre-defined zones

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#5]
The CSAR crash site should happen in pre-defined zones ("pick on at random" kind of zone) to avoid having the site in an area that would be too close of the actual range, or an area that would be too difficult to land around (corner-case extreme).

**Comment by theendsofinvention** [comment]
Make sure that the tasking don't interfere with the usual range tasking

**Comment by 132nd-Entropy** [comment]
this is implemented in version 2.6 :)

**Comment by theendsofinvention** [comment]
Rgr! Closed by e627718605c021dc2d47ce9668a6159155148b5d.
