### ISSUE TITLE
request: merge Master and Develop with 6.4.xx and park 5.x.x  (non-LotATC compatible) on an old branch for savekeeping

### ISSUE THREAD

**Issue by 132nd-Entropy** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#57]
request: merge Master and Develop with 6.4.xx and park 5.x.x on an old branch for savekeeping

**Comment by theendsofinvention** [comment]
There is no need to "park" 5.x.

We can recall it at any time by checking out either the tag or the commit.

:+1:

**Comment by theendsofinvention** [comment]
Fixed in f9070c7b9031cf34cc898b6b714089c000ca1bcb
