### ISSUE TITLE
Increase amount of units available for the ranges

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#6]
~~SUGGESTION/IDEA - pending approval~~

From my experience operating as a J-TAC, the ranges have too few units available to make anything else than very small scale scenarios.

I would like to create a few late-activated group template (infantry platoon, IFV platoon, MBT, mortar team, and so on) that would be available to spawn at will from the F10 menu.

For further reference, the structure would be:

* Create the groups in some remote place and register the spawner with MOOSE
* Define 4 spawning zones for those, one per range
* Create a function that takes two parameters: the range zone, and the group template, to effectively spawn the group
* Register, in the F10 menu, the following new menus:
  * F10 root
      * Ranges
          * Tetra
            * Spawn
                * Mortar Team
                * Infantry Section
                * MBT Platoon
                * IFV Section
          * Tianeti
            * Spawn
                * Mortar Team
                * Infantry Section
                * MBT Platoon
                * IFV Section
          * Dusheti
            * Spawn
                * Mortar Team
                * Infantry Section
                * MBT Platoon
                * IFV Section
          * Marnueli
            * Spawn
                * Mortar Team
                * Infantry Section
                * MBT Platoon
                * IFV Section

N.B.: the groups "Mortar Team", "Infantry Section", "MBT Platoon" and "IFV Section" are only placeholder strings.

If this is accepted, I am willing & able to do the scripting to make this work.

**Comment by 132nd-Entropy** [comment]
Great!! Go for it :)

**Comment by theendsofinvention** [comment]
There should be a possibility to spawn either red or blue groups, depending on the intention of the J-TAC/Flight lead

**Comment by theendsofinvention** [comment]
Make sure that there's a message explicitly stating that RED units have been spawned at any given range, when it happens

**Comment by theendsofinvention** [comment]
@132nd-Entropy testing MIZ can be found here: https://ci.appveyor.com/project/132nd-Entropy/132nd-virtual-wing-training-mission-tblisi/build/artifacts

Dedicated branch: https://github.com/132nd-Entropy/132nd-Virtual-Wing-Training-Mission-Tblisi/tree/feature/issue6-more_units

**Comment by 132nd-Entropy** [comment]
damn nice! I tested, and the arty and the manpads cant be moved. That is because they contain non-movable units (manpad-comms unit and some sort of generator for the arty). I removed those and now they are mobile. will push the changes

**Comment by theendsofinvention** [comment]
Good catch ! Thanks for testing :+1: 

Wait before pushing, I still need to stress-test and to set an upper limit to the amount of units that can be spawned in case someone goes crazy or the system crashes.

Also, as there will be no red units, I can remove one step in the radio menu, which will be quicker for everyone.

**Comment by 132nd-Entropy** [comment]
well there can be red units, but they must be spawned either with weapons hold, or missiles only such as training SAMs. As long as they cant kill anyone, they can be spawned.

about the limit, I dont think we need that really but of course you can put it in. The mission can take a lot of units (this is nothing compared to what we have on OP GT missions, and if someone deliberately kills the mission by chain spawning units, well I dont think its gonna happen

**Comment by theendsofinvention** [comment]
I was more thinking of a bug that would spawn units every tick, but you're right, it never happens.

As for the red units, another concern is that they would fight with the already present blue units, so I would need to define spawning zones outside of the weapons range. That will be tricky mostly for the artillery (artillery should definitely spawn on weapons hold for both sides), but in any case it will be a bit of work.

I suggest we keep this issue open, release a first merge with blue units only, and once the system has been tested a few times with our fellow J-TACs/pilots with only blue units, add the possibility for red units at a later point.

I'll update the project page with the points that have been raised in this issue's comment section.

**Comment by 132nd-Entropy** [comment]
agreed!

**Comment by theendsofinvention** [comment]
Add mobile anti-air units, namely:

Armored mobile AAA
Mobile IR SAM

Maybe: armored mobile advanced SAM (Tungunska, Tor)
