### ISSUE TITLE
Extend CSAR tasking to the other ranges

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#7]
~~SUGGESTION/IDEA - pending approval~~

Now that the CSAR tasking has been tested extensively in Tetra, I would like to extend it further to the other ranges.

The structure in the F10 menu would be:
  * F10 root
      * Ranges
          * Tetra
            * CSAR 
                * CSAR menu under here (the 3 options currently available)
          * Marnueli
            * CSAR 
                * CSAR menu under here (the 3 options currently available)
          * Dusheti
            * CSAR 
                * CSAR menu under here (the 3 options currently available)
          * Tianeti
            * CSAR 
                * CSAR menu under here (the 3 options currently available)

If this is approved, I am willing and able to make the required edits and scripting to make this work.

**Comment by 132nd-Entropy** [comment]
sure!

**Comment by 132nd-Entropy** [comment]
I think this is a good idea, but at the same time super low priority. If people want to practice CSAR they might as well move over to TETRA

**Comment by theendsofinvention** [comment]
Roger, I'll keep the issue open but won't prioritize it.

**Comment by 132nd-Entropy** [comment]
having a hard time keeping up, Id like to close the issue as there is so much more urgent stuff going on so wecan focus better
