### ISSUE TITLE
Add SEAD training options

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#8]
SUGGESTION/IDEA - pending approval

Original idea from Dex: 132nd.Dex: Are these going to be randomized in any way? Maybe add the option to add in spessific SAM/AAA units to train SEAD

Allow a selection of blue/red anti air units to be spawned at the different ranges to allow for specific SEAD training.

**Comment by theendsofinvention** [comment]
As for #6, make sure that there's a message explicitly stating that RED units have been spawned at any given range, when it happens

**Comment by 132nd-Entropy** [comment]
so there are trianing SAMs at the south of the airfield, ist that not what you are looking for, Dex?
